package com.ems.dao;

import java.util.List;
import java.util.Map;

import com.ems.exception.DataAccessException;
import com.ems.model.EventRegistrationReport;
import com.ems.model.Registration;
import com.ems.model.RegistrationTicket;

public interface RegistrationDao {

    /**
     * Retrieves confirmed registrations for a specific event
     *
     * @param eventId
     * @return list of event registration reports
     * @throws DataAccessException
     */
    List<EventRegistrationReport> getEventWiseRegistrations(int eventId)
            throws DataAccessException;

    /**
     * Returns total number of registrations for an event
     *
     * @param eventId
     * @return registration count
     * @throws DataAccessException
     */
    int getEventRegistrationCount(int eventId)
            throws DataAccessException;

    /**
     * Retrieves basic user details of all registered users for an event
     *
     * @param eventId
     * @return list of user details
     * @throws DataAccessException
     */
    List<Map<String, Object>> getRegisteredUsers(int eventId)
            throws DataAccessException;

    /**
     * Returns registration count grouped by events of an organizer
     *
     * @param organizerId
     * @return event wise registration counts
     * @throws DataAccessException
     */
    List<Map<String, Object>> getOrganizerWiseRegistrations(int organizerId)
            throws DataAccessException;

    /**
     * Returns ticket sales summary for organizer events
     *
     * @param organizerId
     * @return ticket type wise sales data
     * @throws DataAccessException
     */
    List<Map<String, Object>> getTicketSales(int organizerId)
            throws DataAccessException;

    /**
     * Returns total revenue generated by an organizer
     *
     * @param organizerId
     * @return revenue amount
     * @throws DataAccessException
     */
    double getRevenueSummary(int organizerId)
            throws DataAccessException;

    /**
     * Returns all user ids registered for an event
     *
     * @param eventId
     * @return list of user ids
     * @throws DataAccessException
     */
    List<Integer> getRegisteredUserIdsByEvent(int eventId)
            throws DataAccessException;

    /**
     * Retrieves registration details by id
     *
     * @param registrationId
     * @return registration details or null if not found
     * @throws DataAccessException
     */
    Registration getById(int registrationId)
            throws DataAccessException;

    /**
     * Updates registration status
     *
     * @param registrationId
     * @param status
     * @throws DataAccessException
     */
    void updateStatus(int registrationId, String status)
            throws DataAccessException;

    /**
     * Retrieves ticket details associated with a registration
     *
     * @param registrationId
     * @return list of registration tickets
     * @throws DataAccessException
     */
    List<RegistrationTicket> getRegistrationTickets(int registrationId)
            throws DataAccessException;
}
